### ISSUE TITLE
v1.3 이슈 리포트

### ISSUE THREAD

**Issue by dewoweb** [easylogic/gnuboard5-summernote#10]
안녕하세요. dewoweb 입니다.
해결을 하고 코드를 올릴 심산이었으나
아직 섬머노트에 대한 근본적인 이해도는 낮은지라 감이 안 잡히네요.
보고드리겠습니다.

[버그]
텍스트 편집 기능이 동작하지 않습니다.
볼드, 이탤릭, 밑줄, 취소선 및
글씨 색상, 배경색 등의 텍스트 속성 일체가 적용되지 않습니다.

[의견]
일전에 포스팅한 소스에 첨언하신 주석에 약간의 상이점이 보여서 말씀 올립니다.
35line @ upload.php
} else if (!getimagesize($tmp_name)) { // check file size, if filesize is zero, return fail
getimagesize 함수는 파일의 캐퍼시티(용량)을 리턴하는 것이 아니라
이미지파일 해상도의 가로(width) 세로(height)를 배열로 리턴합니다.
예를들어
test.jpg가 있을 경우에 너비가 800픽셀 높이가 600픽셀이라면
$resolution = getimagesize('./test.jpg');
이 경우에
$resolution[0] 에는 800
$resolution[1] 에는 600
이 담겨집니다. 결론적으로 getimagesize를 통하여 이미지인지 아닌지를 판별하는 것은
파일의 캐퍼시티를 통한 확인이 아니라 이미지 파일일 경우 해상도 정보가 있으며
이미지 파일이 아닐경우 null이기 때문에 판별이 가능한 것입니다.
때문에
} else if (!getimagesize($tmp_name)) { // check image resolution, if resolution is null, return fail
이 적절한 해석이라고 보여집니다.

[결론]
섬머노트 최신 빌드가 아마도 easylogic께서 적용하신 이전 빌드의 섬머노트와는
구조적으로 많이 다른듯 싶습니다. 수고스러우시더라도 한번 더 디버깅을 통하여
기능의 정상적인 작동이 되었으면 하는 바램입니다. 받아가기만 하는 것 같아 죄송합니다.
감사합니다.

**Comment by easylogic** [comment]
@dewoweb  리포팅 감사합니다. 

크롬에서 테스트 중인데요. 

Bold, Italic, Underline, 취소선, 윗첨자, 아랫첨자 모두 정상 작동 하는걸 확인했습니다. 

색상의 경우 현재 선택된 색상 버튼을 클릭해도 적용이 되지 않네요. (이건 버그네요. 서머노트쪽에서 수정할 수 있도록 이야기 하겠습니다.) 

지금 어디서 테스트 하시는지 알면 좀 더 좋은 정보가 될 것 같습니다. 

감사합니다. 

ps. 주석에 관련된건 말씀 하신게 맞는 것 같습니다. 그 쪽으로 수정해놓을게요.

**Comment by dewoweb** [comment]
아 저는 파이어폭스 정식빌드 최신버전입니다.
http://summernote.org/
에서 샘플페이지로 테스트해보니
파이어폭스, 크롬 모두 잘 동작합니다.

**Comment by easylogic** [comment]
@dewoweb 파이어폭스에서 포커스 동작이 완전 이상하네요. 

심각한데요. ^^;;;;; 안 알려주셨으면 모를뻔 했네요. 파폭을 주 브라우저로 안써서. 

스페이스만 눌러도 엔터 효과가 되버리네요.  왜 이렇지 ? ㅠㅠ 

파폭에서 일단 잘 동작하도록 구성을 다시 해야할 것 같습니다. 

감사합니다.

**Comment by easylogic** [comment]
@dewoweb  summernote 버그인줄 알았는데. 

디버깅 해보니깐  $("div").is(":focus") 가  jquery 1.8 에서 무조건 false 군요. ㅡㅡ; 

저게 false 가 되버리면 summernote 에서 현재 사용하고 있는 에디터를 인식을 못하는 문제가 생겨서 정상적으로 동작을 안하는거였습니다. 

gnuboard5 에서 1.8 이 기본으로 쓰이는지라  조금 애매하네요. 

일단은 코드를 조금 수정해서 되겠끔 구성했습니다.  

나중에 테스트 한번 해주세요.

**Comment by easylogic** [comment]
@dewoweb  

긴급 패치 올렸습니다. 

https://github.com/easylogic/gnuboard5-summernote/releases/tag/v1.3.1

확인 한번 해주시면 감사하겠습니다.

**Comment by easylogic** [comment]
@dewoweb  혹시 gnuboard5 쓰실 때  theme 적용해서 쓰시나요?  jquery 버전을 얼마로 쓰시나요?

**Comment by dewoweb** [comment]
그누보드5 기준으로
순정 theme에 basic를 사용합니다.
js파일들은 add나 modify없이
remove만 하고있는 상황이구요.
jquery 관련 src도 수정한 것은 없습니다.
올려주신 빌드 테스트하고 보고드리겠습니다.

**Comment by dewoweb** [comment]
Firefox 43.0.4
IE 11.0.9600(11.0.27)
Chrome 47.0.2526.111
(Windows7 64bit)

모두 정상작동 확인하였습니다.
감사합니다.

**Comment by dewoweb** [comment]
번외로 사담입니다만
제가 예전에 개발일을 하다가
이제는 자영업을 하던 와중에(물건 파는 일입니다.)
그러다 올해 큰 교통사고를 당해서 건강이 많이 안 좋아져서
실내에서 할 수 있는 일로.... 다시 개발쪽으로 돌아왔습니다.
회사원이거나 어디 소속된 건 아니고
예전부터 생각해오던 소소한 아이디어를 가지고
스타트업 사업을 시작하는 중입니다.
와중에 섬머노트가 제 개발취지에 딱 맞는다 싶어서
채택을 한 상황인데 정말 많은 도움이 되어 주셨습니다.
혹 나중에 만나뵙게 될 영광이 있다면 근사한 식사라도 한끼
대접하고 싶습니다. 감사합니다!

**Comment by easylogic** [comment]
@dewoweb 

해결되셨다니 천만 다행입니다. ^^ 

코드가 잘 못 되서 괜한 불편함을 주지 않는가 해서 걱정이었는데 말이죠. ^^ 

일단 전 현재 summernote 메인 개발자로 있어서 누구라도 좀 더 많이 썼으면 좋겠다는 취지로 만들어봤어요. 

작으나마 도움이 되셨다니 기분이 좋습니다. ^^ 하시는 일 번창하시도록 기원할게요. 

ps. 혹시 collabee 다니시나요?

**Comment by dewoweb** [comment]
collabee 라는 단어는 처음 접하는지라 검색해 보았습니다.
클라우드 업무툴 같은 그런 것 같군요.
소규모 스타트업에 잘 어울리는 시스템으로 보이네요.
저는 현재 1인 창업 후 서비스 런칭을 위해서 개발 중입니다.

2010년대 이후로는 개발을 해보지 않았는데
웹생태계가 참 많이 바뀌었군요.
이전에 급부상 하던 Ajax니 Jquery니 하는 것들이
이제는 너무나 당연시 되어있고 웹표준은 더욱이 말할 것도 없구요.

좋은 주말 보내시길 바랍니다.

(아 그러고보니 교통사고가 올해가 아니라 작년15년도군요. 4월 1일에 사고나고
의식차리고보니 5월이고 회복하니 가을이더군요. 오히려 사고가 좋은 기회라
생각하고 열심히 개발 중입니다. 이지로직님께서도 하시는 일 잘 되시길 바랍니다!)

**Comment by easylogic** [comment]
@dewoweb 

제가 많은 도움은 되진 않겠지만 필요하신 부분 있으면  언제든지 말씀해주세요.. 

좋은 주말 되세요. ^^ 화이팅입니다.
