### ISSUE TITLE
관리자 창에서 사용이 안됩니다.

### ISSUE THREAD

**Issue by illite** [easylogic/gnuboard5-summernote#2]
관리자 창에서 나오지 않습니다.
내용관리 같은 창에서 기존의 에디터는 출력이 되어 에디터를 사용할 수 있으나, 섬머노트는 나오지 않습니다.
하드코딩을 해야할 것 같은데 어디를 봐야할지 도통 알 수가 없어서 이슈를 남깁니다.

**Comment by easylogic** [comment]
어떤 메뉴에서 안나오나요? 

일단 플러그인을 복사 하신다음에. 

[관리자 > 기본환경 설정 > 에디터 선택 ] 란에서 summernote 를 선택하고 저장해주시면 됩니다. 

제가 확인해본 메뉴는  정상적으로 summernote 가 나오고 있습니다. 

회원메일 입력 
게시판관리 > 게시판 추가  
게시판관리 > 1:1 문의 설정 
게시판관리 > 내용 관리 추가 
게시판 관리 > FAQ 추가 

혹서 에디터를 설정 하신 다음에  로그인을 다시 하셨나요?

**Comment by easylogic** [comment]
@illite 혹시 계속 안되시나요?

**Comment by illite** [comment]
다른서버에 새로 설치해서 테스트하니 잘됩니다..
제가 이것저것 만져봐서 아무래도 안되나 봅니다.
번거롭게 하여 죄송합니다.
즐거운 추석 연휴 보내시길 바랍니다.
감사합니다.
