### ISSUE TITLE
이미지 업로드시 취약점 보완 (이미지 파일 유효성 검토)

### ISSUE THREAD

**Issue by dewoweb** [easylogic/gnuboard5-summernote#9]
[ upload.php 취약점 보완 ]

-------------------기존 소스-----------------------
if (!preg_match("/(jpe?g|gif|bmp|png)$/i", $filename_ext)) {
    // error
    echo json_encode(array('success' => false, 'error' => 100)); // file type error 
} else {

-------------------보완 소스-----------------------
$mime_result = ' '.@mime_content_type($tmp_name).@shell_exec('file -bi '. $tmp_name);
// 서버 환경이나 데몬 버전에 따라 앞에 ' ' 스페이스 문자를 삽입하지 않을 경우
// 문자열 중에 일부 문자가 유실되는 버그 방지를 위하여 스페이스 문자 한칸 삽입

if (!preg_match("/(jpe?g|gif|bmp|png)$/i", $filename_ext)) {
    @unlink($tmp_name);
    echo json_encode(array('success' => false, 'error' => 100));
}
else if ( !stripos($mime_result, 'jpeg') &&
    !stripos($mime_result, 'jpg') &&
    !stripos($mime_result, 'gif') &&
    !stripos($mime_result, 'bmp') &&
    !stripos($mime_result, 'png') ) {
    @unlink($tmp_name);
    echo json_encode(array('success'=> false, 'error' => 100));
}
else if (!getimagesize($tmp_name)) {
    @unlink($tmp_name);
    echo json_encode(array('success'=> false, 'error' => 100));
}
else {

**Comment by dewoweb** [comment]
[ Example ]
예를 들어서 텍스트 파일을 만들어서
SQL 쿼리나 스크립트 작성 후
hello.jpg 로 파일명 변경후 업로드시
에디터(textarea) 본문에는 아무런 변화가 없으나
서버에 파일이 업로드 됩니다.

위의 소스 코드는 해당 상황에서 파일을 삭제하여
서버 및 클라이언트에 대한 보안 위협을 방지합니다.

**Comment by easylogic** [comment]
소중한 코드 감사합니다. 
코드 다시 업데이트 해야겠네요.

**Comment by easylogic** [comment]
master 에 적용되었습니다. 

master 코드 참고하세요 ~
